config/routes.rb
Rails.application.routes.draw do
  resources :fasteners
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_scope :user do
  #  root to: 'devise/sessions#new'
  #end

  root to: 'fasteners#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fastener.rb
class Fastener < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable , :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fasteners_controller.rb
class FastenersController < ApplicationController
  before_action :set_fastener, only: [:show, :edit, :update, :destroy]

  # GET /fasteners
  # GET /fasteners.json
  def index
    @fasteners = Fastener.all
  end

  # GET /fasteners/1
  # GET /fasteners/1.json
  def show
  end

  # GET /fasteners/new
  def new
    @fastener = Fastener.new
  end

  # GET /fasteners/1/edit
  def edit
  end

  # POST /fasteners
  # POST /fasteners.json
  def create
    @fastener = Fastener.new(fastener_params)

    respond_to do |format|
      if @fastener.save
        format.html { redirect_to @fastener, notice: 'Fastener was successfully created.' }
        format.json { render :show, status: :created, location: @fastener }
      else
        format.html { render :new }
        format.json { render json: @fastener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fasteners/1
  # PATCH/PUT /fasteners/1.json
  def update
    respond_to do |format|
      if @fastener.update(fastener_params)
        format.html { redirect_to @fastener, notice: 'Fastener was successfully updated.' }
        format.json { render :show, status: :ok, location: @fastener }
      else
        format.html { render :edit }
        format.json { render json: @fastener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fasteners/1
  # DELETE /fasteners/1.json
  def destroy
    @fastener.destroy
    respond_to do |format|
      format.html { redirect_to fasteners_url, notice: 'Fastener was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fastener
      @fastener = Fastener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fastener_params
      params.require(:fastener).permit(:year, :model, :location, :fastener, :specification, :citation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fasteners_helper.rb
module FastenersHelper
end

app/views/fasteners/_form.html.erb
<%= form_for(fastener) do |f| %>
  <% if fastener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fastener.errors.count, "error") %> prohibited this fastener from being saved:</h2>

      <ul>
      <% fastener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :fastener %>
    <%= f.text_field :fastener %>
  </div>

  <div class="field">
    <%= f.label :specification %>
    <%= f.text_field :specification %>
  </div>

  <div class="field">
    <%= f.label :citation %>
    <%= f.text_field :citation %>
  </div>

  <div class="actions across">
    <%= f.submit %>
  </div>
<% end %>

app/views/fasteners/edit.html.erb
<h1>Editing Fastener</h1>

<%= render 'form', fastener: @fastener %>

<%= link_to 'Show', @fastener, class: 'button w5 across' %>
<%= link_to 'Back', fasteners_path, class: 'button w5 across' %>

app/views/fasteners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fastener Specifications</h1>

<table>
  <thead>
    <tr>
      <th class="col1">Year</th>
      <th class="col2">Model</th>
      <th class="col3">Location</th>
      <th class="col4">Fastener</th>
      <th class="col5">Specification</th>
      <th class="col6">Citation</th>
      <th colspan="3" class="col7">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @fasteners.each do |fastener| %>
      <tr>
        <td class="cell"><%= fastener.year %></td>
        <td class="cell"><%= fastener.model %></td>
        <td class="cell"><%= fastener.location %></td>
        <td class="cell"><%= fastener.fastener %></td>
        <td class="cell"><%= fastener.specification %></td>
        <td class="cell"><%= fastener.citation %></td>
        <td><%= link_to 'Show', fastener, class: 'button w5' %></td>
        <td><%= link_to 'Edit', edit_fastener_path(fastener), class: 'button w5' %></td>
        <td><%= link_to 'Destroy', fastener, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button w5' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fastener', new_fastener_path, class: 'button w10' %>

app/views/fasteners/new.html.erb
<h1>New Fastener</h1>

<%= render 'form', fastener: @fastener %>

<%= link_to 'Back', fasteners_path, class: 'button w5 across' %>

app/views/fasteners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @fastener.year %>
</p>

<p>
  <strong>Model:</strong>
  <%= @fastener.model %>
</p>

<p>
  <strong>Location:</strong>
  <%= @fastener.location %>
</p>

<p>
  <strong>Fastener:</strong>
  <%= @fastener.fastener %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @fastener.specification %>
</p>

<p>
  <strong>Citation:</strong>
  <%= @fastener.citation %>
</p>

<%= link_to 'Edit', edit_fastener_path(@fastener), class: 'button w5 across' %>
<%= link_to 'Back', fasteners_path, class: 'button w5 across' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnofficialZeroManualDb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <header>

    </header>
    <div class="main-body">
      <div class="flash">
        <% flash.each do |key, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{key}") %>
        <% end %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>